version: "3"
networks:
  expense:
volumes:
  mysql: # docker volume create mysql
services:
  mysql:
    image: techsravani/mysql:v1
    container_name: mysql
    volumes: # Map volumes
    - mysql:/var/lib/mysql # -v mysql /var/lib/mysql  # Source 
  backend:
    image: techsravani/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: techsravani/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend
